### ISSUE TITLE
ENV variables for DB Connection Configuration

### ISSUE THREAD

**Issue by digitaltopo** [azavea/franklin#393]
**Describe the bug**
Looking at https://github.com/azavea/franklin/blob/master/application/src/main/scala/com/azavea/franklin/database/Config.scala#L15 it seems that the database connection can be configured via environment variables (via `Properties.envOrElse`), but it's unclear to me if these env vars are actually being pulled up by https://github.com/azavea/franklin/blob/master/application/src/main/scala/com/azavea/franklin/commands/DatabaseConfig.scala, which seems to only use the values passed in via flags from https://github.com/azavea/franklin/blob/master/application/src/main/scala/com/azavea/franklin/commands/DatabaseOptions.scala

I've tried to run Franklin `serve` (via docker) with the env variables present and without using the `--db-host` etc flags, but Franklin complains that the database isn't configured properly.

**Expected behavior**
Env variables used for database connection options

**Additional context**
I'm new to Scala, so any clarification how these pieces of code work together would be appreciated. Thank you!

**Comment by jisantuc** [comment]
Hey @digitaltopo, that file is leftover from a previous iteration on application config. It's only used in tests. It shouldn't really be in `src/main` but I think is leftover from our template. Sorry for the mess!

It is possible using [`decline`](http://ben.kirw.in/decline/) to fallback from the command line to an environment variable, and we do that in [another project](https://github.com/raster-foundry/granary/blob/master/api/src/main/scala/com/rasterfoundry/granary/options/DatabaseOptions.scala#L31-L43). The analogous configuration in Franklin is [here](https://github.com/azavea/franklin/blob/master/application/src/main/scala/com/azavea/franklin/commands/DatabaseOptions.scala). If you'd like to take a stab at that, I think it would be small and pretty focused PR

**Comment by digitaltopo** [comment]
Understood, thanks for the clarification. I think what was further confusing was in [the docker-compose example in the docs](https://azavea.github.io/franklin/docs/introduction#using-docker-compose), there were environment variables being set. The instructions work, but probably because Franklin's default database configuration options work for the setup in the `docker-compose.yml`, not because the env variables are actually being used:

```
 ...
 franklin:
    image: quay.io/azavea/franklin:latest
    depends_on:
      database:
        condition: service_healthy
    command:
      - serve
    volumes:
      - ./:/opt/franklin/
    environment: 
      - ENVIRONMENT=development
      - POSTGRES_URL=jdbc:postgresql://database.service.internal/ <--
      - POSTGRES_NAME=franklin <--
      - POSTGRES_USER=franklin <--
      - POSTGRES_PASSWORD=franklin <-- 
    links:
      - database:database.service.internal
    ports:
      - "9090:9090"
``` 

I've created a [PR](https://github.com/azavea/franklin/pull/398) that adds environment variables for both the database configuration and API configuration a la the helpful example you shared above. I've also updated the docs to include references to them. Thanks for the help and please let me know if this looks good!
