### ISSUE TITLE
API_WITH_TRANSACTIONS and API_WITH_TILES environment variables don't work

### ISSUE THREAD

**Issue by aripollak** [azavea/franklin#969]
**Describe the bug**
In my docker-compose.yml, I have the following:

```
  franklin:
    image: quay.io/azavea/franklin:latest
    depends_on:
      database:
        condition: service_healthy
    command:
      - serve
    volumes:
      - ./:/opt/franklin/
    environment:
      - ENVIRONMENT=development
      - DB_HOST=database.service.internal
      - DB_NAME=franklin
      - DB_USER=franklin
      - DB_PASSWORD=franklin
      - API_WITH_TRANSACTIONS=true
      - API_WITH_TILES=true
    links:
      - database:database.service.internal
    ports:
      - "9090:9090"
```

When I start the container with` docker-compose up -d`, the tile and transaction endpoints aren't listed in the links/conformsTo, but the API_WITH_TRANSACTIONS and API_WITH_TILES environment variables are documented as being things that should work. If I instead add `--with-transactions` `--with-tiles` to the command, I do see those extra endpoints as expected. 

**Expected behavior**
I'd expect API_WITH_TRANSACTIONS=true and API_WITH_TILES=true environment variables to enable those extra endpoints.

**Additional context**
